# Docker compose for influxdb v2 test
version: '3'

services:
  influxdb1:
    image: influxdb:2.0
    container_name: influxdb1
    ports:
      - 8086:8086
    volumes:
      - ./influxdb1:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=db1

  influxdb2:
    image: influxdb:2.0
    container_name: influxdb2
    ports:
      - 8087:8086
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=db2

  inmate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inmate
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - influxdb1
      - influxdb2
